{"name": "keyboard", "event": "press", "vk": 90}
{"name": "keyboard", "event": "release", "vk": 90}
{"name": "keyboard", "event": "press", "vk": 72}
{"name": "keyboard", "event": "release", "vk": 72}
{"name": "keyboard", "event": "press", "vk": 65}
{"name": "keyboard", "event": "press", "vk": 78}
{"name": "keyboard", "event": "press", "vk": 71}
{"name": "keyboard", "event": "release", "vk": 65}
{"name": "keyboard", "event": "release", "vk": 78}
{"name": "keyboard", "event": "release", "vk": 71}
{"name": "keyboard", "event": "press", "vk": 81}
{"name": "keyboard", "event": "press", "vk": 73}
{"name": "keyboard", "event": "release", "vk": 81}
{"name": "keyboard", "event": "press", "vk": 85}
{"name": "keyboard", "event": "release", "vk": 73}
{"name": "keyboard", "event": "release", "vk": 85}
{"name": "keyboard", "event": "press", "vk": 88}
{"name": "keyboard", "event": "release", "vk": 88}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 84}
{"name": "keyboard", "event": "press", "vk": 73}
{"name": "keyboard", "event": "release", "vk": 84}
{"name": "keyboard", "event": "press", "vk": 69}
{"name": "keyboard", "event": "release", "vk": 73}
{"name": "keyboard", "event": "release", "vk": 69}
{"name": "keyboard", "event": "press", "vk": 90}
{"name": "keyboard", "event": "press", "vk": 72}
{"name": "keyboard", "event": "release", "vk": 90}
{"name": "keyboard", "event": "press", "vk": 85}
{"name": "keyboard", "event": "release", "vk": 72}
{"name": "keyboard", "event": "release", "vk": 85}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
