{"name": "mouse", "event": "click", "target": "left", "action": true, "location": {"x": 732, "y": 586}}
{"name": "mouse", "event": "click", "target": "left", "action": false, "location": {"x": 732, "y": 586}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 732, "y": 586}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 733, "y": 587}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 735, "y": 589}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 737, "y": 590}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 741, "y": 593}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 745, "y": 595}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 751, "y": 597}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 757, "y": 598}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 763, "y": 601}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 770, "y": 604}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 778, "y": 608}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 787, "y": 611}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 795, "y": 614}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 802, "y": 617}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 808, "y": 620}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 814, "y": 623}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 820, "y": 625}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 825, "y": 627}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 830, "y": 629}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 835, "y": 631}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 840, "y": 634}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 847, "y": 638}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 853, "y": 642}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 859, "y": 647}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 865, "y": 654}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 872, "y": 659}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 880, "y": 665}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 888, "y": 672}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 896, "y": 678}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 904, "y": 685}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 913, "y": 691}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 922, "y": 699}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 931, "y": 706}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 941, "y": 714}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 951, "y": 721}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 959, "y": 727}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 968, "y": 734}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 975, "y": 740}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 982, "y": 746}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 988, "y": 750}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 992, "y": 754}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 996, "y": 758}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 998, "y": 760}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1000, "y": 762}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1001, "y": 763}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1002, "y": 764}}
{"name": "mouse", "event": "click", "target": "left", "action": true, "location": {"x": 1002, "y": 764}}
{"name": "mouse", "event": "click", "target": "left", "action": false, "location": {"x": 1002, "y": 764}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 1002, "y": 764}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 999, "y": 766}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 994, "y": 773}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 987, "y": 779}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 977, "y": 786}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 964, "y": 792}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 949, "y": 799}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 930, "y": 806}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 907, "y": 813}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 883, "y": 819}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 856, "y": 825}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 827, "y": 832}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 799, "y": 835}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 768, "y": 837}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 741, "y": 837}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 711, "y": 837}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 684, "y": 837}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 653, "y": 834}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 624, "y": 830}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 595, "y": 825}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 566, "y": 820}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 541, "y": 819}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 516, "y": 817}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 499, "y": 817}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 480, "y": 817}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 462, "y": 814}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 448, "y": 813}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 435, "y": 811}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 425, "y": 809}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 415, "y": 808}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 407, "y": 806}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 399, "y": 805}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 393, "y": 805}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 387, "y": 805}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 381, "y": 805}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 377, "y": 805}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 374, "y": 805}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 372, "y": 805}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 371, "y": 805}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 370, "y": 805}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 370, "y": 805}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 369, "y": 805}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 368, "y": 805}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 367, "y": 805}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 365, "y": 805}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 365, "y": 805}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 364, "y": 805}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 363, "y": 805}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 363, "y": 805}}
{"name": "mouse", "event": "click", "target": "left", "action": true, "location": {"x": 363, "y": 805}}
{"name": "mouse", "event": "click", "target": "left", "action": false, "location": {"x": 363, "y": 805}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 362, "y": 805}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 360, "y": 805}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 355, "y": 805}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 350, "y": 804}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 340, "y": 802}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 331, "y": 800}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 318, "y": 798}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 306, "y": 794}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 291, "y": 791}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 272, "y": 787}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 255, "y": 780}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 235, "y": 773}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 216, "y": 766}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 196, "y": 759}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 179, "y": 753}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 164, "y": 746}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 152, "y": 741}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 141, "y": 736}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 131, "y": 733}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 125, "y": 730}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 119, "y": 728}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 115, "y": 727}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 111, "y": 725}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 108, "y": 724}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 105, "y": 723}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 103, "y": 723}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 102, "y": 723}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 100, "y": 722}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 98, "y": 722}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 97, "y": 722}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 95, "y": 722}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 93, "y": 722}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 91, "y": 722}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 88, "y": 721}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 85, "y": 720}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 83, "y": 720}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 82, "y": 720}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 79, "y": 719}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 77, "y": 718}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 77, "y": 718}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 76, "y": 718}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 75, "y": 718}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 75, "y": 718}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 73, "y": 718}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 72, "y": 718}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 71, "y": 718}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 69, "y": 718}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 69, "y": 718}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 68, "y": 718}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 66, "y": 718}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 64, "y": 717}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 64, "y": 717}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 63, "y": 717}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 62, "y": 717}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 61, "y": 717}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 59, "y": 716}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 59, "y": 716}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 57, "y": 716}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 56, "y": 715}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 55, "y": 714}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 55, "y": 714}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 54, "y": 713}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 54, "y": 713}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 53, "y": 713}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 53, "y": 713}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 51, "y": 712}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 50, "y": 711}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 49, "y": 711}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 48, "y": 710}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 47, "y": 710}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 45, "y": 709}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 45, "y": 709}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 44, "y": 709}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 43, "y": 709}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 43, "y": 709}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 42, "y": 709}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 41, "y": 709}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 41, "y": 709}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 40, "y": 709}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 39, "y": 709}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 39, "y": 709}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 38, "y": 709}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 37, "y": 709}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 37, "y": 709}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 36, "y": 709}}
{"name": "mouse", "event": "move", "target": "default", "action": "default", "location": {"x": 36, "y": 709}}
{"name": "mouse", "event": "click", "target": "left", "action": true, "location": {"x": 36, "y": 709}}
{"name": "mouse", "event": "click", "target": "left", "action": false, "location": {"x": 36, "y": 709}}
